<!--
 *@author Fabio Pratta <fabiobrotas@hotmail.com> 
 *@copyright Copyright - publico.fundacaoceu.org.br
 *@version 1.0 19/02/2014
-->
<h3>Registro</h3>
<?php if($this->messages):?>
<p>
    <?php echo $this->messages[0]; ?>
</p>

<?php else: ?>

<?php 
$form = $this->form;
$form->setAttribute('action',$this->url('appuser-register',array('controller'=>'index','action'=>'register')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formCollection($form);
echo $this->form()->closeTag();
?>

<?php endif; ?>
