<div class="panel panel-info">
    <div class="panel-heading">
        <h4>
            <strong>Vendedores</strong>
            <a class="btn btn-success navbar-right" href="<?php echo $this->url("appuser-admin/default", array('cotroller'=>'vendedores','action' => 'new')); ?>">Novo</a> 
        </h4>
    </div>
    
     <div class="panel-body">

    <table class="table table-striped table-responsive">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Email</th>
                <th>Ação</th>
            </tr>
        </thead>
        <tbody>
            <?php foreach ($this->data as $entity): ?>
                <tr>
                    <td><?php echo $entity->getId(); ?></td>
                    <td><?php echo $entity->getNome(); ?></td>
                    <td><?php echo $entity->getEmail(); ?></td>
                    <td>
                        <a class="label label-info" href="<?php echo $this->url('appuser-admin/default', array('controller' => 'vendedores', 'action' => 'edit', 'id' => $entity->getId())); ?>">Editar</a> | 
                        <a class="label label-danger" href="<?php echo $this->url('appuser-admin/default', array('controller' => 'vendedores', 'action' => 'delete', 'id' => $entity->getId())); ?>">Deletar</a>
                    </td>
                </tr>
            <?php endforeach; ?>
        </tbody>
    </table>
    <br/>
    <?php echo $this->paginationControl($this->data, 'Sliding', 'partials/paginator'); ?>
     </div>
</div>