
<div class="panel  panel-primary">
    <div class="panel-heading">Seja bem vindo,</div>
    <div class="panel-body">
        <div class="alert alert-info">Efetue o login para acesso ao sistema
            <a href="<?php echo $this->url("appuser-auth") ?>" class="alert-link">Efetuar Login</a>
        </div>
    </div>
    <div class="panel-footer">em caso de duvidas <a href="mailto:fabiopratta@fundacaoceu.org.br">Envie um email :)</a></div>
</div>

